build-job:
  stage: build
  tags:
    - homlistic
  script:
    - echo "Hello v5, $GITLAB_USER_LOGIN!" 
    - /home/gitlab-runner/dev/flutter/bin/dart run build_runner build
    - /home/gitlab-runner/dev/flutter/bin/flutter build web --output /home/gitlab-runner/dev/flutter_build

deploy-prod:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - homlistic
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production