build-job:
  stage: build
  tags:
    - homlistic
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy-prod:
  stage: deploy
  tags:
    - homlistic
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production