#!/bin/bash

mkdir -p assets_webp

# List of carousel images to convert
images=(
  "assets/AD0425_GRT_CHARLAP_2.webp"
  "assets/AD0425_GRT_CHARLAP_3.webp"
  "assets/AD0425_GRT_CHARLAP_4.webp"
  "assets/AD0425_GRT_CHARLAP_5.webp"
  "assets/AD0425_GRT_CHARLAP_6.webp"
  "assets/AD0425_GRT_CHARLAP_7.webp"
  "assets/AD0425_GRT_CHARLAP_8.webp"
  "assets/AD0425_GRT_CHARLAP_9.webp"
  "assets/AD0425_GRT_CHARLAP_11.webp"
  "assets/Bayside_01.jpg"
  "assets/Bayside_02.jpg"
  "assets/Bayside_03.jpg"
  "assets/Bayside_04.jpg"
  "assets/Bayside_05.jpg"
  "assets/Betty_01.jpg"
  "assets/Betty_02.jpg"
  "assets/Betty_03.jpg"
  "assets/Betty_04.jpg"
  "assets/Doris_01.jpg"
  "assets/Doris_02.jpg"
  "assets/Doris_03.jpg"
  "assets/Doris_04.jpg"
  "assets/E 84th St_Social-24.jpg"
  "assets/E 84th St_Social-30.jpg"
  "assets/E 84th St_Social-33.jpg"
  "assets/E 84th St_Social-37.jpg"
  "assets/ellen_01.jpg"
  "assets/ellen_02.jpg"
  "assets/ellen_03.jpg"
  "assets/ellen_04.jpg"
  "assets/ellen_05.jpg"
  "assets/GregRick_01.jpg"
  "assets/GregRick_02.jpg"
  "assets/GregRick_03.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_0-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_1-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_2-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_3-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_4-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_5-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_6-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_8-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_9-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_10.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_11-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_12-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_13-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_14.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_15-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_16-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_17-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_18-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_19.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_20-scaled.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_2364_col_21.jpg"
  "assets/harlem-rectory_grt-architects_dezeen_herp2.webp"
  "assets/Kim_01.jpg"
  "assets/Kim_02.jpg"
  "assets/Kim_03.jpg"
  "assets/Visionaire_00.jpg"
  "assets/Visionaire_01.jpg"
  "assets/Visionaire_02.jpg"
  "assets/Visionaire_03.jpg"
  "assets/Visionaire_04.jpg"
  "assets/Visionaire_05.jpg"
  "assets/Visionaire_06.jpg"
  "assets/Visionaire_07.jpg"
  "assets/Wooster_01.jpg"
  "assets/Wooster_02.jpg"
  "assets/Wooster_03.jpg"
  "assets/Wooster_04.jpg"
  "assets/Wooster_05.jpg"
  "assets/Wooster_06.jpg"
  "assets/Wooster_08.jpg"
  "assets/harlem.png"
  "assets/ad.png"
)


for img in "${images[@]}"; do
  filename=$(basename "$img")
  name="${filename%.*}"
  echo "Converting $img to assets_webp/$name.webp ..."
  
  # Convert & resize with quality 80, max width 1200px, keep aspect ratio (height 0)
  cwebp -q 80 -resize 1200 0 "$img" -o "assets_webp/$name.webp"
done

echo "Conversion complete. WebP images are in assets_webp/"
